In [1]:
import pandas as pd
import numpy as np

In [16]:
data = pd.read_csv("vgsales_clean_2.csv")

In [17]:
data

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,Nintendo Entertainment System,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,Game Boy,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16284,16596,Woody Woodpecker in Crazy Castle 5,Game Boy Advance,2002,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16285,16597,Men in Black II: Alien Escape,GameCube,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16286,16598,SCORE International Baja 1000: The Official Game,PlayStation 2,2008,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16287,16599,Know How 2,Nintendo DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16288,16600,Spirits & Spells,Game Boy Advance,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [28]:
data = data.groupby(level = ["Genre","Year"]).agg({"NA_Sales": sum, "EU_Sales": sum, "JP_Sales": sum, "Other_Sales": sum, "Global_Sales": sum})

In [29]:
data.columns

Index(['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'], dtype='object')

In [42]:
genres = set()
for (genre, year), row in data.iterrows():
    genres.add(genre)
genres = list(genres)

In [54]:
out_data = {}
for (genre, year), row in data.iterrows():
    if year in out_data:
        out_data[year][genre] = row["Global_Sales"]
    else:
        out_data[year] = {}
        out_data[year][genre] = row["Global_Sales"]

In [55]:
X = []
for year in out_data:
    x = [year]
    d = out_data[year]
    for genre in genres:
        if genre in d:
            x.append(d[genre])
        else:
            x.append(0)
    X.append(x)

In [61]:
out = pd.DataFrame(X, columns = ["year"] + list(genres))

In [62]:
out.to_csv("aggregated_genre.csv")

In [63]:
out = out[["year"] + sorted(genres)]

In [64]:
out

,year,Action,Adventure,Fighting,Misc,Platform,Puzzle,Racing,Role-Playing,Shooter,Simulation,Sports,Strategy
0,1980,0.34,0.00,0.77,2.71,0.00,0.00,0.00,0.00,7.07,0.00,0.49,0.00
1,1981,14.84,0.00,0.00,0.00,6.93,2.24,0.48,0.00,10.04,0.45,0.79,0.00
2,1982,6.52,0.00,0.00,0.87,5.03,10.03,1.57,0.00,3.79,0.00,1.05,0.00
3,1983,2.86,0.40,0.00,2.14,6.93,0.78,0.00,0.00,0.48,0.00,3.20,0.00
4,1984,1.85,0.00,0.00,1.45,0.69,3.14,5.95,0.00,31.10,0.00,6.18,0.00
5,1985,3.52,0.00,1.05,0.00,43.17,3.21,0.00,0.00,1.00,0.03,1.96,0.00
6,1986,13.74,0.00,0.00,0.00,9.39,0.00,1.96,2.52,3.89,0.00,5.57,0.00
7,1987,1.12,4.38,5.42,0.00,1.74,0.00,0.00,4.65,0.71,0.00,3.72,0.00
8,1988,1.75,0.00,0.00,0.00,27.73,5.58,2.14,5.88,0.51,0.03,3.60,0.00
9,1989,4.64,0.00,0.00,1.28,20.66,37.75,0.00,2.20,1.20,0.00,5.72,0.00
10,1990,6.39,0.00,0.00,0.00,22.97,6.00,6.26,4.52,0.00,1.14,2.11,0.00
11,1991,6.76,2.24,0.39,0.08,7.64,3.24,1.14,3.25,2.00,2.14,2.41,0.94
12,1992,3.83,12.24,15.25,4.94,13.42,4.84,9.04,6.86,0.29,2.14,2.95,0.36
13,1993,1.81,0.07,8.75,0.30,18.67,3.17,0.36,5.59,3.08,0.19,3.18,0.81
14,1994,1.55,3.74,8.47,2.86,28.74,1.53,2.19,7.11,8.30,2.73,8.39,3.56
15,1995,3.57,0.72,14.85,6.40,16.69,2.71,6.09,14.26,4.15,4.18,7.98,6.51
16,1996,20.58,4.19,18.06,10.68,28.23,3.91,28.24,43.96,6.91,11.33,17.45,5.61
17,1997,27.58,4.96,11.76,5.69,21.85,5.89,31.91,21.79,22.17,9.65,30.02,7.71
18,1998,39.44,9.05,31.66,11.94,29.88,6.34,27.90,28.09,9.80,7.11,41.79,13.47
19,1999,27.78,7.60,14.26,20.65,20.82,1.36,37.27,49.09,12.25,11.44,30.29,18.46
20,2000,34.04,2.98,20.22,15.54,16.06,3.82,19.99,29.03,6.81,3.38,41.19,8.50
21,2001,59.39,9.12,18.12,16.40,39.28,8.00,55.81,22.06,24.77,19.54,51.43,7.55
22,2002,86.77,11.05,25.02,15.67,45.97,5.34,30.20,45.13,48.58,10.81,65.42,5.56
23,2003,67.93,2.14,23.73,23.82,42.89,2.42,52.19,30.28,27.14,21.21,56.11,7.99
24,2004,76.26,8.51,16.78,26.21,47.34,8.43,47.86,53.95,46.95,10.85,63.68,7.19
25,2005,85.69,8.53,19.72,59.81,23.56,20.45,56.42,28.55,41.60,49.27,59.54,5.37
26,2006,66.58,11.47,22.55,67.35,49.80,10.90,34.09,57.73,38.37,21.77,136.16,4.27
27,2007,106.50,24.39,17.61,91.06,35.59,24.00,39.17,43.89,71.04,48.97,98.20,9.42
28,2008,136.39,25.02,35.38,87.03,35.70,15.59,70.66,59.83,59.51,46.76,95.34,11.69
29,2009,139.36,20.68,32.15,76.94,41.09,20.31,34.19,47.90,69.89,33.71,138.52,12.56
30,2010,117.64,16.53,14.89,96.86,31.90,11.18,34.93,70.52,77.41,21.99,92.53,13.87
31,2011,118.96,15.98,22.68,56.08,28.11,5.11,35.00,53.37,99.36,15.26,56.99,8.90
32,2012,122.01,5.99,9.51,22.92,18.53,1.76,14.46,47.81,72.86,13.38,30.93,3.33
33,2013,125.22,6.61,7.21,25.65,25.12,0.99,13.04,44.92,62.80,8.67,41.55,6.33
34,2014,99.02,6.06,16.15,23.68,8.89,1.49,16.69,45.85,66.00,5.55,46.66,0.99
35,2015,70.70,8.03,7.78,11.69,6.05,0.70,7.92,36.44,66.15,5.62,41.54,1.82
36,2016,19.90,1.79,3.86,1.17,2.07,0.00,1.64,6.76,18.22,0.39,14.60,0.50
37,2017,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.04,0.00,0.00,0.00,0.00
38,2020,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.29,0.00,0.00

In [65]:
out.to_csv("aggregated_genre.csv")